controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/users/auth

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

admin_dashboard:
    path: /admin
    controller:
    methods: GET

random_path:
    path: /sardor
    controller: App\Controller\AuthController::login
    methods: GET